server:
  port: 9000
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-app:
            registration:
              client-id: "cashcard-client"
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods: "client_secret_basic"
              authorization-grant-types: "client_credentials"
              scopes:
                - cashcard:read
                - cashcard:write