name: Generic Tools Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the Workshop Image"
        required: true
        default: "v0.0.1"

jobs:
  amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Updating and Installing Tools
        run: |
          sudo apt update
          sudo apt install -y bc pv
         

      - name: Build
        run: |
          mkdir -p /tmp/artifacts
          cp $(which pv) /tmp/artifacts/pv-amd64
          cp $(which bc) /tmp/artifacts/bc-amd64
          
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          name: tools
          tag_name: ${{github.event.inputs.version}}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: /tmp/artifacts/pv-amd64,/tmp/artifacts/bc-amd64

  arm64:
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          dockerRunArgs: |
            --volume "/tmp/artifacts:/artifacts"
          install: |
            apt update -q -y
            apt install -q -y pv bc
         
          run: |
            cp $(which pv) "/artifacts/pv-arm64"
            cp $(which bc) "/artifact/bc-arm64"
            ls -lrt /artifacts
            
          
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          name: tools
          tag_name: ${{github.event.inputs.version}}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: "/tmp/artifacts/pv-arm64","/tmp/artifacts/bc-arm64"
