name: Generic Tools Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the Workshop Image"
        required: true
        default: "0.0.1"

jobs:
  amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Updating and Installing Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev zlib1g-dev binutils-arm-none-eabi gcc-arm-none-eabi gcc-arm-none-eabi-source libncurses-dev
         

      - name: Build
        run: |
          curl -L -s https://www.ivarch.com/programs/sources/pv-1.8.0.tar.gz -o pv.tgz
          tar xvzf pv.tgz
          cd pv-1.8.0
          ./configure && make
          mv pv pv-amd64
          # make clean
          # ./configure --host=aarch64-unknown-linux-gnu --target=aarch64-unknown-linux-gnu && make      
          # mv pv pv-arm64
          # make clean
          # ./configure --host=arm-none-linux-eabi --target=arm-none-linux-eabi && make
          # mv pv pv-aarch64
          # ls -lrt


      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          name: pv
          tag_name: v1.8.0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: pv-1.8.0/pv-amd64
  arm64:
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          install: |
            #binutils-arm-none-eabi gcc-arm-none-eabi gcc-arm-none-eabi-source build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev zlib1g-dev libncurses-dev
            apt update -q -y
            apt install -q -y pv
         
          run: |
            cp $(which pv) "/artifacts/pv-arm64"
            # curl -L -s https://www.ivarch.com/programs/sources/pv-1.8.0.tar.gz -o pv.tgz
            # tar xvzf pv.tgz
            # cd pv-1.8.0
            # ./configure && make
            # mv pv /artifacts/pv-arm64
          
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          name: pv
          tag_name: v1.8.0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: ${PWD}/artifacts/pv-arm64
