name: Generic Tools Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the Workshop Image"
        required: true
        default: "0.0.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Updating and Installing Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev zlib1g-dev gcc-arm-linux-gnueabi gnat-12
          #sudo install apt-file
          #sudo apt-file update

      - name: Build
        run: |
          curl -L -s https://www.ivarch.com/programs/sources/pv-1.8.0.tar.gz -o pv.tgz
          tar xvzf pv.tgz
          cd pv-1.8.0
          ./configure && make
          mv pv pv-amd64
          ./configure --host=arm-linux-gnueabi && make      
          mv pv pv-arm64
          ./configure --host=aarch64 && make
          mv pv pv-aarch64
          ls -lrt


      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          name: pv
          tag_name: v1.8.0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: pv-1.8.0/pv-amd64,pv-1.8.0/pv-arm64,pv-1.8.0/pv-aarch64
