name: JWT for Linux ARM64

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout JWT
      uses: actions/checkout@v4
      with:
        repository: mike-engel/jwt-cli
        ref: main
    - name: Adding ToolChain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true
    - name: Building Release
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target aarch64-unknown-linux-gnu
    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        name: jwt-cli-arm64
        tag_name: 6.0.0
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: target/aarch64-unknown-linux-gnu/release/jwt
